# Generated by Django 4.2.7 on 2024-07-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_dob_customer_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='product_id',
            field=models.CharField(default='DEFAULT_ID', max_length=20),
        ),
    ]
