# Generated by Django 4.2.7 on 2024-07-27 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='last_name',
            new_name='name',
        ),
    ]
