# Generated by Django 4.2.7 on 2024-07-27 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_rename_first_name_customer_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='social_media_links',
        ),
    ]
