# Generated by Django 4.2.7 on 2024-07-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_customer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='purchase_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
